sudo: false

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

script: coverage run tests.py && coverage report -m

install:
  - pip install .
  - pip install coverage
  - pip install codecov

after_success:
  - codecov
